# Generated by Django 5.1.15 on 2026-04-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_student_group_number_alter_teacher_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='student_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимум студентов'),
        ),
    ]
