# Generated by Django 5.1.15 on 2026-04-17 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа работы')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код типа работы')),
            ],
            options={
                'verbose_name': 'Тип работы',
                'verbose_name_plural': 'Типы работ',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема работы')),
                ('norm_control_status', models.CharField(choices=[('passed', 'Пройден'), ('needs_changes', 'Есть исправления'), ('pending', 'В ожидании'), ('not_sent', 'Не отправлено')], default='pending', max_length=20, verbose_name='Статус нормоконтроля')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='users.department', verbose_name='Кафедра')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='users.student', verbose_name='Студент')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_works', to='users.teacher', verbose_name='Руководитель')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='works.worktype', verbose_name='Тип работы')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='WorkCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role', models.CharField(choices=[('supervisor', 'Руководитель'), ('norm_controller', 'Нормоконтролер')], max_length=20, verbose_name='Роль автора')),
                ('items', models.JSONField(default=list, verbose_name='Список правок')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Правки учтены')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата устранения правок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_corrections', to='users.teacher', verbose_name='Автор правок')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='works.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Правки к работе',
                'verbose_name_plural': 'Правки к работам',
                'ordering': ('-created_at',),
            },
        ),
    ]
