# Generated by Django 5.1.15 on 2026-05-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_workrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('passed', 'Пройден'), ('needs_changes', 'Есть исправления'), ('pending', 'В ожидании'), ('not_sent', 'Не отправлено')], default='not_sent', max_length=30, verbose_name='Статус работы'),
        ),
        migrations.AlterField(
            model_name='work',
            name='norm_control_status',
            field=models.CharField(choices=[('done', 'Сдана'), ('not_sent', 'Не отправлена'), ('in_progress', 'В работе'), ('student_edit', 'Правки от студента'), ('supervisor_edit', 'Правки от руководителя'), ('normcontroller_edit', 'Правки от нормоконтролера')], default='not_sent', max_length=20, verbose_name='Статус нормоконтроля'),
        ),
    ]
