# Generated by Django 5.1.15 on 2026-06-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_work_status_alter_work_norm_control_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('rejected', 'Отклонено'), ('accepted', 'Подтверждено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
