# Generated by Django 5.1.15 on 2026-04-18 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department', verbose_name='Кафедра'),
        ),
    ]
