# Generated by Django 5.1.15 on 2026-05-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contacts',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Контакты'),
        ),
    ]
